from enum import StrEnum


class Classifications(StrEnum):
    GROCERIES = "GROCERIES"
    EATING_OUT = "EATING_OUT"
    TRANSPORTATION = "TRANSPORTATION"
    HOUSING = "HOUSING"
    HEALTHCARE = "HEALTHCARE"
    PERSONAL_CARE = "PERSONAL_CARE"
    ENTERTAINMENT = "ENTERTAINMENT"
    SAVINGS_AND_INVESTMENTS = "SAVINGS_AND_INVESTMENTS"
    DEBT_PAYMENT = "DEBT_PAYMENT"
    MISC = "MISC"
